export const mockApi = {
  getHashtags: jest.fn(),
  getPhotos: jest.fn(),
  findPhoto: jest.fn(),
  addHashtag: jest.fn(),
  updateHashtag: jest.fn(),
  deletePhoto: jest.fn(),
  increaseViews: jest.fn(),
  editHashtags: jest.fn(),
  addPhoto: jest.fn(),
  uploadPhoto: jest.fn(),
  getPosts: jest.fn(),
  getPost: jest.fn(),
  addPost: jest.fn(),
  editPost: jest.fn(),
  deletePost: jest.fn(),
  getProjects: jest.fn(),
  addProject: jest.fn(),
  editProject: jest.fn(),
  deleteProject: jest.fn(),
  getProjectHashtags: jest.fn(),
  sendContactMessage: jest.fn(),
};
